

dir_suffix: 'TRIP_CRISPR'

input_file:
  mapping:
    idx_A:
      - [/home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-A_TAGTATCAGC_R1.fastq, /home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-A_TAGTATCAGC_R2.fastq]
      - 10
    idx_B:
      - [/home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-B_TCTCTATGCG_R1.fastq, /home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-B_TCTCTATGCG_R2.fastq]
      - 10

structure:
  mapping: |
    ID      5'      3'      type    req     second-read     pos   keep-bases
    index   %i      -       const   present False   fixed   -
    map_pat1a       GTCACAAGGGCCGGC   -       const   present False   fixed   -
    const_bar       CACAA\{16\}TGATC  -       const_bar       present False   fixed   -
    rev_map_complement      -       TTAACCCTAGAAAGATAATCATATTGTGACGTAC      const   -       False   var   -
    rev_map GTACGTCACAATATGATTATCTTTCTAGGGTTAA      -       const   present True    fixed   -
    fwd_map_complement      -       GATCA[BC]CTCGAGTTGTGGCCGGCCCTTGTGAC     const_bar_comp  -       True    var   -

lev_dist: 2

min_count:
    map: 3

bowtie:
  index:  /home/NFS/users/r.schep/data/bowtie2/hg38/hg38
  options:
      '1': ['--very-sensitive-local']
      '2': ['--very-sensitive-local']
max_dist:
  '1': 500
  '2': 20
